// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Objekt
    {
        public Objekt()
        {
            OdrzavanjeObjekta = new HashSet<OdrzavanjeObjekta>();
        }

        public int Id { get; set; }
        public int DionicaId { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public string TipObjekta { get; set; }
        public int? NadmorskaVisina { get; set; }
        public int? Stacionaza { get; set; }
        public int? DimenzijeM { get; set; }
        public double? GeografskaSirina { get; set; }
        public double? GeografskaDuzina { get; set; }

        public virtual Dionice Dionica { get; set; }
        public virtual ICollection<OdrzavanjeObjekta> OdrzavanjeObjekta { get; set; }
    }
}