// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{

    public partial class ParkGospVoz
    {
        public int ParkingId { get; set; }
        public int DionicaId { get; set; }
        public double Stacionaža { get; set; }
        public string Naziv { get; set; }
        public double GeoSirinaUlaz { get; set; }
        public double GeoDuzinaUlaz { get; set; }
        public int BrojMjesta { get; set; }
        public double? CijenaPoSatu { get; set; }
        public string StranaCesteUlaz { get; set; }

        public virtual Dionice Dionica { get; set; }
    }
}