// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Sadrzaj
    {
        public Sadrzaj()
        {
            RadnoVrijeme = new HashSet<RadnoVrijeme>();
        }

        public int Id { get; set; }
        public string Naziv { get; set; }
        public double? GeografskaSirina { get; set; }
        public double? GeografskaDuzina { get; set; }
        public int TipSadrzajaId { get; set; }
        public int OdmoristeId { get; set; }

        public string TipSadrzajaNaziv
        {
            get
            {
                try
                {
                    return TipSadrzaja.Naziv;
                }
                catch (NullReferenceException)
                {
                    return "";
                }
            }
        }
        public virtual Odmoriste Odmoriste { get; set; }
        public virtual TipSadrzaja TipSadrzaja { get; set; }
        public virtual ICollection<RadnoVrijeme> RadnoVrijeme { get; set; }
    }
}