// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Autoceste
    {
        public Autoceste()
        {
            Dionice = new HashSet<Dionice>();
        }

        public string Oznaka { get; set; }
        public string Pocetak { get; set; }
        public string Kraj { get; set; }
        public int DuljinaKm { get; set; }
        public string Koncesionar { get; set; }

        public virtual Koncesionari KoncesionarNavigation { get; set; }
        public virtual ICollection<Dionice> Dionice { get; set; }
    }
}