// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class OdrzavanjeObjekta
    {
        public int Id { get; set; }
        public DateTime Datum { get; set; }
        public string Odrzavatelj { get; set; }
        public string Ishod { get; set; }
        public string Opis { get; set; }
        public int ObjektId { get; set; }
        public int TipId { get; set; }

        public virtual Objekt Objekt { get; set; }
        public virtual TipOdrzavanja Tip { get; set; }
    }
}