// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Dionice
    {
        public Dionice()
        {
            Kamere = new HashSet<Kamere>();
            Obavijesti = new HashSet<Obavijesti>();
            Objekt = new HashSet<Objekt>();
            Odmoriste = new HashSet<Odmoriste>();
            ParkGospVoz = new HashSet<ParkGospVoz>();
        }

        public int Id { get; set; }
        public int IzlaznaPostaja { get; set; }
        public int UlaznaPostaja { get; set; }
        public int DuljinaKm { get; set; }
        public string OznakaAutoceste { get; set; }

        public virtual NaplatnaPostaja IzlaznaPostajaNavigation { get; set; }
        public virtual Autoceste OznakaAutocesteNavigation { get; set; }
        public virtual NaplatnaPostaja UlaznaPostajaNavigation { get; set; }
        public virtual ICollection<Kamere> Kamere { get; set; }
        public virtual ICollection<Obavijesti> Obavijesti { get; set; }
        public virtual ICollection<Objekt> Objekt { get; set; }
        public virtual ICollection<Odmoriste> Odmoriste { get; set; }
        public virtual ICollection<ParkGospVoz> ParkGospVoz { get; set; }
    }
}