// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Encpostaja
    {
        public int Encid { get; set; }
        public TimeSpan VrijemeOtvaranja { get; set; }
        public TimeSpan VrijemeZatvaranja { get; set; }
        public string KontaktBroj { get; set; }
        public string Ime { get; set; }
        public int? NaplatnaId { get; set; }
        public int? NaplatnaStaza { get; set; }

        public virtual NaplatnaPostaja Naplatna { get; set; }
    }
}