// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Kamere
    {
        public Kamere()
        {
            Slike = new HashSet<Slike>();
        }

        public int Id { get; set; }
        public int DionicaId { get; set; }
        public string Naziv { get; set; }
        public double? GeografskaSirina { get; set; }
        public double? GeografskaDuzina { get; set; }

        public virtual Dionice Dionica { get; set; }
        public virtual ICollection<Slike> Slike { get; set; }
    }
}