// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class NaplatnaPostaja
    {
        public NaplatnaPostaja()
        {
            CjenikIzlaz = new HashSet<Cjenik>();
            CjenikUlaz = new HashSet<Cjenik>();
            DioniceIzlaznaPostajaNavigation = new HashSet<Dionice>();
            DioniceUlaznaPostajaNavigation = new HashSet<Dionice>();
        }

        public int NaplatnaId { get; set; }
        public string Ime { get; set; }
        public double GeoDuzina { get; set; }
        public double GeoSirina { get; set; }

        public virtual Encpostaja Encpostaja { get; set; }
        public virtual ICollection<Cjenik> CjenikIzlaz { get; set; }
        public virtual ICollection<Cjenik> CjenikUlaz { get; set; }
        public virtual ICollection<Dionice> DioniceIzlaznaPostajaNavigation { get; set; }
        public virtual ICollection<Dionice> DioniceUlaznaPostajaNavigation { get; set; }
    }
}